/**
 * Parity tests for the signature verification this app does server-side.
 *
 * The vectors are Ed25519 signatures produced by `lib/crypto.py` over bytes
 * built by `approver/protocol.py` — the registration handler's own key and its
 * own reply format (`approver/CLAUDE.md` §6). If this goes red, `register` will
 * reject every answer the real handler sends.
 *
 * Run: npm test
 */
import assert from "node:assert/strict";
import test from "node:test";

import { verifyEd25519 } from "./keys.ts";
import { registrationReplySigningBytes } from "./protocol.ts";

/** Generated by lib/crypto.py — an ed25519 pair whose private half we discarded. */
const SERVER_PUBLIC = "+Ar9n88yIA1qlP3mH+KQ+IM9N21neUapjN7kbaF5WDI=";

const ACCEPTED = {
  fields: { v: 1, ok: true, key_id: "approver-web", nonce: "bm9uY2U=", ts: 1737345600, error: "" },
  bytes: "registration-reply\n1\ntrue\napprover-web\nbm9uY2U=\n1737345600\n",
  sig: "tADAmaZQwl7+oYr5E/74JHPU7NKAS9hZfNAfVMWhI7GNOtrdPUIdZeWU3jze5sktoKR+ww7DHw+umoO8WMpcBw==",
};

const REJECTED = {
  fields: { v: 1, ok: false, key_id: "", nonce: "bm9uY2U=", ts: 1737345600, error: "token unknown" },
  bytes: "registration-reply\n1\nfalse\n\nbm9uY2U=\n1737345600\ntoken unknown",
  sig: "3b/Li5fa3zPVgSC7pOR/Whj1ZucCrQKbVxa6b+9QfY+dC0Xd/OhLvlcMGzdO+DSj8KsorrqdhX2qlQWmgR3UAQ==",
};

const decoder = new TextDecoder();

test("registrationReplySigningBytes matches protocol.registration_reply_signing_bytes", () => {
  for (const v of [ACCEPTED, REJECTED]) {
    assert.equal(decoder.decode(registrationReplySigningBytes(v.fields)), v.bytes);
  }
});

test("verifyEd25519 accepts what lib/crypto.py signed", () => {
  for (const v of [ACCEPTED, REJECTED]) {
    assert.ok(verifyEd25519(SERVER_PUBLIC, registrationReplySigningBytes(v.fields), v.sig));
  }
});

test("verifyEd25519 rejects a flipped verdict", () => {
  // The whole point of signing rejections: "token unknown" cannot become an ack.
  const flipped = registrationReplySigningBytes({ ...REJECTED.fields, ok: true });
  assert.equal(verifyEd25519(SERVER_PUBLIC, flipped, REJECTED.sig), false);
});

test("verifyEd25519 rejects a replayed nonce", () => {
  const replayed = registrationReplySigningBytes({ ...ACCEPTED.fields, nonce: "b3RoZXI=" });
  assert.equal(verifyEd25519(SERVER_PUBLIC, replayed, ACCEPTED.sig), false);
});

test("verifyEd25519 rejects another key's signature", () => {
  const other = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
  assert.equal(
    verifyEd25519(other, registrationReplySigningBytes(ACCEPTED.fields), ACCEPTED.sig),
    false,
  );
});

test("verifyEd25519 is fail-safe on junk input", () => {
  const bytes = registrationReplySigningBytes(ACCEPTED.fields);
  for (const [key, sig] of [
    ["not base64 !!", ACCEPTED.sig],
    ["", ACCEPTED.sig],
    [SERVER_PUBLIC, "not base64 !!"],
    [SERVER_PUBLIC, ""],
    ["QQ==", ACCEPTED.sig], // right encoding, wrong length
  ] as const) {
    assert.equal(verifyEd25519(key, bytes, sig), false);
  }
});
