// The cross-language parity vectors (CLAUDE.md §10.11 **tier 2**).
//
// Every other suite in this directory asserts something this firmware decided.
// This one asserts something the *other language* decided: `vectors/parity_vectors.h`
// is generated by `approver/protocol.py` and `lib/crypto.py` themselves, and the
// tests below run the device's own assemblers against it, case by case.
//
// **Why the tier exists at all.** Two implementations of §7 that drift apart do
// not produce an error anywhere: the device signs bytes nobody asked for, the
// hook recomputes different ones, verification fails, and Claude Code falls back
// to its own terminal — which is indistinguishable, from the desk, from a
// responder that is not answering. There is no log line, no red light and no
// failing assertion in either half. The only place that disagreement can be made
// to fail loudly is here.
//
// **Two things have to be true for it to mean anything**, and they are checked
// on opposite sides of the language boundary:
//
//   * the device reproduces the vectors — this file;
//   * the vectors are still what Python produces *today* —
//     `tests/test_esp32_vectors.py`, which regenerates them on every `pytest`
//     run and fails if the committed header has gone stale.
//
// Without the second, a fixture is a pasted literal with extra steps: it goes on
// passing forever after `protocol.py` changes underneath it. That is exactly the
// state the three string literals this file replaced were in.

#include <cstdint>
#include <cstring>

#include "registration.h"
#include "signing.h"
#include "unity.h"
#include "vectors/parity_vectors.h"

namespace {

constexpr char kPoison = '\x7f';

// A message the test can print when it fails. Unity's string comparison shows
// both sides, and for a `\n`-joined field list that is the only readable form —
// a diff of two 200-character strings on one line is a diff nobody reads.
void AssertBytes(const char *what, const char *expected, size_t expected_length,
                 const char *actual, size_t actual_length) {
    TEST_ASSERT_EQUAL_UINT32_MESSAGE(expected_length, actual_length, what);
    TEST_ASSERT_EQUAL_STRING_MESSAGE(expected, actual, what);
}

// ---------------------------------------------------------------------------
// §7 — a decision's signing bytes.

void test_every_decision_vector_is_reproduced(void) {
    for (const auto &vector : vectors::kDecisions) {
        protocol::Decision decision;
        decision.v = vector.v;
        decision.ts = vector.ts;
        decision.session_id = vector.session_id;
        decision.nonce = vector.nonce;
        decision.tool_name = vector.tool_name;
        decision.input_sha256 = vector.input_sha256;
        decision.behavior = vector.behavior;

        char out[protocol::kSigningBytesMax];
        std::memset(out, kPoison, sizeof out);
        const size_t n = protocol::DecisionSigningBytes(decision, out, sizeof out);

        AssertBytes(vector.name, vector.signing_bytes, vector.signing_length, out, n);
    }
}

// **`kSigningBytesMax` is a promise, and this is the vector that collects it.**
// The generator emits one case with every field at the bound `signing.h`
// declares and both integers at their widest — so if that constant is ever a
// byte short, an ordinary large request stops being signable and this fails
// rather than a device going quiet in the field.
void test_the_largest_message_python_can_produce_still_fits(void) {
    const vectors::DecisionVector *vector = vectors::FindDecision("allow-at-every-bound");
    TEST_ASSERT_NOT_NULL_MESSAGE(vector, "the bound vector was renamed or removed");
    TEST_ASSERT_TRUE_MESSAGE(vector->signing_length < protocol::kSigningBytesMax,
                             "kSigningBytesMax does not hold what §7 can produce");
}

// ---------------------------------------------------------------------------
// §6 — the registration reply's signing bytes.

void test_every_registration_reply_vector_is_reproduced(void) {
    for (const auto &vector : vectors::kRegistrationReplies) {
        char out[protocol::kReplySigningBytesMax];
        std::memset(out, kPoison, sizeof out);
        const size_t n = protocol::RegistrationReplySigningBytes(
            vector.v, vector.ok, vector.key_id, vector.nonce, vector.ts, vector.error, out,
            sizeof out);

        AssertBytes(vector.name, vector.signing_bytes, vector.signing_length, out, n);
    }
}

void test_the_largest_reply_python_can_produce_still_fits(void) {
    for (const auto &vector : vectors::kRegistrationReplies) {
        TEST_ASSERT_TRUE_MESSAGE(vector.signing_length < protocol::kReplySigningBytesMax,
                                 vector.name);
    }
}

// ---------------------------------------------------------------------------
// The fixture itself.

// **A suite that iterates an empty array passes.** So the counts are asserted:
// a generator that wrote a truncated header, or a `#include` that silently
// resolved to something else, must fail here rather than report a green run over
// nothing at all. The numbers are lower bounds rather than exact ones, because
// adding a vector should not be a test to update.
void test_there_are_vectors_to_check(void) {
    TEST_ASSERT_GREATER_OR_EQUAL_UINT32(6, vectors::kDecisionCount);
    TEST_ASSERT_GREATER_OR_EQUAL_UINT32(6, vectors::kRegistrationReplyCount);
    TEST_ASSERT_EQUAL_UINT32(vectors::kDecisionCount,
                             sizeof vectors::kDecisions / sizeof vectors::kDecisions[0]);
}

// The lookup the other suites reach for. A vector that has been renamed must
// answer null and be caught, never be quietly skipped — which is what would
// happen if `FindDecision` returned the first entry on a miss.
void test_an_unknown_vector_is_not_silently_substituted(void) {
    TEST_ASSERT_NULL(vectors::FindDecision("no-such-vector"));
    TEST_ASSERT_NOT_NULL(vectors::FindDecision("allow-bash"));
}

// **Both the integers and the bytes travel, and this says which is which.** The
// device echoes `ts` as an `int64_t` it never re-derives; the two extreme vectors
// are the ones a `double` cannot carry, so their presence is part of the
// contract rather than a nicety somebody could tidy away.
void test_the_extreme_timestamps_are_still_covered(void) {
    bool saw_max = false;
    bool saw_min = false;
    for (const auto &vector : vectors::kDecisions) {
        saw_max = saw_max || vector.ts == INT64_MAX;
        saw_min = saw_min || vector.ts == INT64_MIN;
    }
    TEST_ASSERT_TRUE_MESSAGE(saw_max, "no vector carries the widest positive ts");
    TEST_ASSERT_TRUE_MESSAGE(saw_min, "no vector carries INT64_MIN");
}

// §10.3 puts `approvals.*` on the LAN, so a field that is not ASCII is ordinary
// traffic rather than a curiosity: Python encodes it as utf-8 and the device
// copies the bytes out of the JSON. The vector proves those are the same thing,
// and this asserts the vector is still there to prove it.
void test_a_field_that_is_not_ascii_is_still_covered(void) {
    const vectors::DecisionVector *vector = vectors::FindDecision("allow-non-ascii-session");
    TEST_ASSERT_NOT_NULL_MESSAGE(vector, "the utf-8 vector was renamed or removed");

    bool high_byte = false;
    for (const char *p = vector->session_id; *p != '\0'; ++p) {
        high_byte = high_byte || (static_cast<unsigned char>(*p) >= 0x80);
    }
    TEST_ASSERT_TRUE_MESSAGE(high_byte, "the utf-8 vector no longer holds a non-ASCII byte");
}

}  // namespace

void RegisterVectorTests(void) {
    RUN_TEST(test_every_decision_vector_is_reproduced);
    RUN_TEST(test_the_largest_message_python_can_produce_still_fits);

    RUN_TEST(test_every_registration_reply_vector_is_reproduced);
    RUN_TEST(test_the_largest_reply_python_can_produce_still_fits);

    RUN_TEST(test_there_are_vectors_to_check);
    RUN_TEST(test_an_unknown_vector_is_not_silently_substituted);
    RUN_TEST(test_the_extreme_timestamps_are_still_covered);
    RUN_TEST(test_a_field_that_is_not_ascii_is_still_covered);
}
